### ISSUE TITLE
[TypeScript] Optional event properties are typed  as "null | undefined"

### ISSUE THREAD

**Issue by andrecrimb** [avohq/avo#45]
Event properties set as optional ("Sometimes sent") on the platform are typed as "null | undefined"

Eg.

```typescript
export interface ExampleEventProperties {
   name: string;
   city: string | null | undefined;
}
```

Such approach makes tsc complain, when a "optional prop" isn't specified at the generated function 

```typescript
 Avo.exampleEvent({
     name: "John",
  }),

// tsc complains saying "Property 'city' is missing in type ...."
```

This issue could be solved setting the prop as optional using the question mark `prop?: {type}`

```typescript
export interface ExampleEventProperties {
   name: string;
   city?: string;
}
```

```
avo --version
2.0.2
```

**Comment by hugihlynsson** [comment]
Hi @andrecrimb! I believe that the typing for optional properties is like that by design—to have the developer make a deliberate decision whether to send the desired type or use `null | undefined`. It makes it less likely that someone forgets to send an optional value. @alex-tpom6oh might have more info on the reasoning behind this decision.

**Comment by andrecrimb** [comment]
@hugihlynsson thanks for your response! I would be glad to hear the the reasoning behind this decision.

**Comment by paraboom** [comment]
It'd still be nice to hear about the optional fields in the schemas.

It's very inconvenient to specify all **optional** fields when I want to trigger an Analytical event. 

For example, we have a schema with 5 fields, 4 of which are optional.
When we generate an interface using `avo-cli` we get that interface:

```typescript
export interface SomeContext {
  userId: string
  isUserHandsome: boolean | null | undefined
  firstName: string | null | undefined
  lastName: string | null | undefined
  height: string | null | undefined
}
```

and we have to trigger it with all optional fields specified

```typescript
triggerEventWithSomContext({
  userId: 2,
  isUserHandsome: undefined,
  firstName: undefined,
  lastName: undefined,
  height: undefined
})
```

instead of

```typescript
triggerEventWithSomContext({
  userId: 2
})
```

**Comment by hugihlynsson** [comment]
Hi! That's a great way to illustrate the benefits of marking the prop as optional. We've finally written up on why we decided to make the properties explicit. You can read about it here: https://www.avo.app/docs/implementation/explicit-null-in-codegen but the gist is that while it requires a bit more work and isn't as clean, that is outweighed by it's impact on analytics implementation correctness. What you think about this @paraboom?
